### ISSUE TITLE
Can't load placebo v1.4.2

### ISSUE THREAD

**Issue by LightArrowsEXE** [Lypheo/vs-placebo#27]
When updating vs-placebo and trying to run a script, it will return the following error:

```
AttributeError: No attribute with the name placebo exists. Did you mistype a plugin namespace?
```

Downgrading to v1.4.1 fixes this issue. I'm not at all familiar with C, and I can't find any obvious places for the regression to have taken place between 1.4.1 and 1.4.2.

**Comment by quietvoid** [comment]
Is this on Windows?
You probably need `libdovi`.

It's described in the release: https://github.com/Lypheo/vs-placebo/releases/tag/1.4.2

**Comment by LightArrowsEXE** [comment]
Right, my bad. Updated through vsrepo, which doesn't package it with the new update. Thanks!

**Comment by quietvoid** [comment]
It could technically be built to not require it, but that would result in the Dolby Vision mapping not being available.
So I defaulted to build with Dolby Vision support, otherwise it's complicated for end users to build their own on Windows.

**Comment by LightArrowsEXE** [comment]
Yeah, that's fair. I think it's fine to keep it as-is, When downloading it through releases, that information is right there.
We just need vsrepo to also include the file when updating so users don't have to go look around to find out why. ;)
