### ISSUE TITLE
Mystic compiling error when .glsl file is a little large. 

### ISSUE THREAD

**Issue by Omae-Kumiko** [Lypheo/vs-placebo#28]
[nnedi3-nns128-win8x4.zip](https://github.com/Lypheo/vs-placebo/files/9259027/nnedi3-nns128-win8x4.zip)
For example, when I use the shader source  file uploaded above in mpv, it goes well. But `placebo.Shader` reports compiling error like `input:278: error: '' :  syntax error, unexpected IDENTIFIER`. And the `[278]` is below:

> [276] imageStore(out_image, ivec2(gl_GlobalInvocationID) * ivec2(2, 1) + ivec2(1, 0), ret);
[277] }  // hook
[278] ionID) * ivec2(2, 1) + ivec2(1, 0), ret);
[279] }  // hook
[280] void _main_19_0() {
[281] hook();
[282]
[283] }

It is very strange. And this problem also appears when the shader source file is relatively large.

**Comment by quietvoid** [comment]
I'm not able to reproduce any error using both `shader` or `shader_s` on Linux.

Using `clip = clip.placebo.Shader(shader="nnedi3-nns128-win8x4.hook", width=3840, height=1608, filter="mitchell")`

**Comment by Omae-Kumiko** [comment]
Oh, but on my windows11, it just failed. The code is :
>import vapoursynth as vs
from vapoursynth import core
src16 = core.std.BlankClip(width=1920, height=1080, format=vs.YUV444P16, length=1)
shader = src16.placebo.Shader("nnedi3-nns128-win8x4.hook",3840, 2160)
shader.set_output()

And yes, `shader_s`  doesn't have this problem.

**Comment by quietvoid** [comment]
Okay I do get the error on Windows 10.

**Comment by quietvoid** [comment]
Should be fixed in release 1.4.3: https://github.com/Lypheo/vs-placebo/releases/tag/1.4.3
