### ISSUE TITLE
Dolby Vision, `use_dovi` parameter broken?

### ISSUE THREAD

**Issue by damian101** [Lypheo/vs-placebo#32]
I'm using vs-placebo like this:`c = core.placebo.Tonemap(clip=c, src_csp=1, dst_csp=0, dynamic_peak_detection=0, use_dovi=True, dst_max=200, tone_mapping_function=1, tone_mapping_mode=1`. But to my surprise, changing `use_dovi` parameter to `False` never changes anything, I tried it on multiple Dolby Vision sources. My assumption was that setting this parameter to `True` makes vs-placebo use the per-scene Dolby Vision HDR metadata, and in this case would adapt the source peak to the per-scene metadata instead of the global HDR10 metadata. If this is not the case, what is the purpose of this parameter?

**Comment by quietvoid** [comment]
No, `use_dovi` uses the static metadata from the RPU instead of the HDR10 stream.
It's only used for the mastering display max luminance and MaxCLL/FALL.
