### ISSUE TITLE
Feature Request: More supported primaries for SDR target

### ISSUE THREAD

**Issue by damian101** [Lypheo/vs-placebo#33]
`dst_csp=1` reduces primaries to BT.709/sRGB. However, I'd like to reduce them to Display P3 instead. Full BT.2020 primaries should also be an option, and would be fine as the only additional option for me as well, if more convenient.

**Comment by quietvoid** [comment]
I guess we have to add back a param for the target colour primaries.

**Comment by quietvoid** [comment]
Added `dst_prim`. See [pl_color_primaries enum](https://github.com/haasn/libplacebo/blob/master/src/include/libplacebo/colorspace.h#L193) for values.
