### ISSUE TITLE
Changing various parameters has no effect

### ISSUE THREAD

**Issue by damian101** [Lypheo/vs-placebo#34]
Changing `tone_mapping_function`, `src_max` or `dst_max` has no effect. I'm pretty sure it did though in the past.
Recompiling vs-placebo and libplacebo didn't solve it. I'm using Arch Linux, with packages from AUR. Output looks fine though, so it tonemaps properly, I just can't influence how vs-placebo does it.

I'm using vs-placebo Tonemap like this currently:
`c = core.placebo.Tonemap(clip=c, src_csp=1, dst_csp=0, src_max=4000, dynamic_peak_detection=0, dst_max=200, tone_mapping_function=6, tone_mapping_mode=1, gamut_mode=0)`

**Comment by quietvoid** [comment]
Both `src_max` and `dst_max` work fine for me.  
Maybe your clip just isn't bright enough for the difference to be noticeable?

**Comment by damian101** [comment]
> Both `src_max` and `dst_max` work fine for me. Maybe your clip just isn't bright enough for the difference to be noticeable?

Output is bit-identical when changing these values. And for `tone_mapping_function´ and `dst_max` differences should be very visible anyway. 
Changing them in mpv has the expected effect. So libplacebo itself seems to be working...

**Comment by quietvoid** [comment]
I'm not able to reproduce your issue.
See attached zip for my script and results.

[samples.zip](https://github.com/Lypheo/vs-placebo/files/10319994/samples.zip)

**Comment by quietvoid** [comment]
Also, are you testing with `--vo=gpu-next` in mpv? Otherwise it might not be using libplacebo at all.

**Comment by damian101** [comment]
> Also, are you testing with `--vo=gpu-next` in mpv? Otherwise it might not be using libplacebo at all.

Yes, my mpv script looks like this:
```
gpu-api=vulkan
vo=gpu-next
target-prim=bt.709
gamut-mapping-mode=clip
dither-depth=8
dither=error-diffusion

[hdr]
profile-desc=HDR
profile-cond=p["video-params/gamma"] == "pq" or p["video-params/gamma"] == "hlg"
target-peak=200
tone-mapping=bt.2390
tone-mapping-mode=rgb
hdr-compute-peak=no
target-trc=bt.1886
```

**Comment by damian101** [comment]
> I'm not able to reproduce your issue. See attached zip for my script and results.
> 
> [samples.zip](https://github.com/Lypheo/vs-placebo/files/10319994/samples.zip)
> 
> `libplacebo-git v5.229.1.49.g22ce304-1` `vapoursynth-plugin-placebo-git r104.51d0540-1`

Oh, this works... Thanks. Now I can troubleshoot my issue effectively, if it still exists...

**Comment by damian101** [comment]
Well, the parameters work again. Issue is gone. Only thing I did was update my system yesterday, including AUR packages. Thanks for the help.
