### ISSUE TITLE
How to avoid the issue of "placebo.Tonemap:Clip is missing `DolbyVisionRPU` prop for Dolby Vision mapping" ?

### ISSUE THREAD

**Issue by 001comic** [Lypheo/vs-placebo#39]
My environment in Windows10:
 Python 3.11 + VapourSynth R62 + VapourSynth Editor r19-mod-6.2

I'm using these lines for a Dovi clip converted to SDR:
(the clip from [Dolby Vision AD Demo](https://www.demolandia.net/downloads.html?id=78563356) )
```
v1 = core.ffms2.Source(src,width=1920, height=1080,format=vs.YUV420P16)
v2 = core.placebo.Tonemap(clip=v1, src_csp=3, dst_csp=0)
```
When open Preview window of VS Editor, it got these error messages.
```
Error on frame 0 request:
placebo.Tonemap: Clip is missing `DolbyVisionRPU` prop for Dolby Vision mapping!
```
How can I do to avoid this issue?
-- Can this plugin work with ffms2 Resource loader to deal dovi file?
-- Is YUV420P16 a valid format for vs-placebo?
-- Do I need additionally import RPU file or choose vulkan device in the syntax and how to?
(I can extract RPU bin from dvhe video track but I'm not sure it useful or not for this workflow.)

I can't find more info in Readme.md, please guide me more.

**Comment by quietvoid** [comment]
The error means your source plugin doesn't propagate the prop.
You might need to use ffms2 from the latest commits and not the last tagged version.

**Comment by 001comic** [comment]
Thank you @quietvoid for the respond I guess it might be the answer but I can't find the commits version on windows. 
I also tried LSmash loader plugin and met same issue.

**Comment by quietvoid** [comment]
Official L-SMASH also doesn't support it.
Can you try the latest build here: http://avisynth.nl/index.php/FFmpegSource#Alternate_Downloads

It's on AviSynth's site but the plugin is compatible with VapourSynth.

**Comment by 001comic** [comment]
Thank you so much! It's total worked as my wish!
Cheers!
