### ISSUE TITLE
pip warning about versioning deprecation

### ISSUE THREAD

**Issue by iamtherobin** [Lypheo/vs-placebo#46]
>DEPRECATION: vs placebo has a non-standard version number. pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of vs or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063

pip 24.1 is next milestone release

**Comment by quietvoid** [comment]
what does pip have to do with a C plugin?
