### ISSUE TITLE
placebo.Tonemap:Clip is missing DolbyVisionRPU prop for Dolby Vision mapping

### ISSUE THREAD

**Issue by jessielw** [Lypheo/vs-placebo#49]
Having an issue on certain files (linked a sample of one of those below) where I'm getting this error. I looked at this issue here https://github.com/Lypheo/vs-placebo/issues/39 and tested the **FFMS2** build as suggested as well as the latest **FFMS2 5.0** from here https://github.com/FFMS/ffms2/releases/tag/5.0 and they both produce the same error (as well as LSMASH). 

Sample:
https://drive.google.com/file/d/1jG5iM1durg-Likk0rpXx3zLtU4LmJ3Ar/view?usp=sharing

This same file works with **dovi baker**. 

Note: this also fails with https://github.com/Asd-g/avslibplacebo

Thanks!

**Comment by quietvoid** [comment]
Known issue in FFmpeg when the RPU is not the last NAL in an access unit.
You should complain to the author of the sample.

Remuxing the bitstream with `dovi_tool demux` + `dovi_tool mux` fixes it.

**Comment by jessielw** [comment]
> Known issue in FFmpeg when the RPU is not the last NAL in an access unit. You should complain to the author of the sample.
> 
> Remuxing the bitstream with `dovi_tool demux` + `dovi_tool mux` fixes it.

Thanks for looking into it
