### ISSUE TITLE
CRLF problem in shaders

### ISSUE THREAD

**Issue by Alexkral** [Lypheo/vs-placebo#8]
There is a problem with shaders when CRLF is used for Newline instead of LF. There is no error, but the result is not what it should be.

**Comment by Lypheo** [comment]
Sounds like a libplacebo issue seeing as we only pass on the string without any processing.

**Comment by quietvoid** [comment]
libplacebo does indeed only split on newlines, and mpv with `--vo=gpu-next` also uses the same helper as we do.
I suggest simply fixing the file, or open a bug at libplacebo.

**Comment by Alexkral** [comment]
Yes thanks, I fixed the files.

**Comment by quietvoid** [comment]
CRLF files might be fixed in https://github.com/Lypheo/vs-placebo/releases/tag/1.4.3
